<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
    <?php $this->loadPartial('menu', array(
        'items' => array(
            'Team:Admin:Member@addAction' => 'Add a member',
            'Team:Admin:Config@indexAction' => 'Configuration'
        ),
        'actions' => array(
            'data' => $members,
            'save' => 'Team:Admin:Member@tweakAction',
            'delete' => 'Team:Admin:Member@deleteAction'
        )
    )); ?>
</div>

<div class="card">
    <?php $this->loadPartial('items-per-page', array('caption' => 'Team')); ?>

    <form>
        <div class="table-responsive">
            <?= $this->widget(new GridViewWidget($members, array(
                'batch' => true,
                'pk' => 'id',
                'tableClass' => 'table table-hover table-bordered table-striped',
                'columns' => array(
                    array(
                        'column' => 'id',
                        'label' => '#'
                    ),

                    array(
                        'column' => 'photo',
                        'value' => function($member){
                            return Element::image($member->getImageUrl('400x200'), array('class' => 'img-fluid'));
                        }
                    ),

                    array(
                        'column' => 'name'
                    ),

                    array(
                        'column' => 'order',
                        'value' => function($member){
                            return Element::number(sprintf('order[%s]', $member->getId()), $member->getOrder(), array('class' => 'form-control', 'min' => '0'));
                        }
                    ),

                    array(
                        'column' => 'published',
                        'value' => function($member){
                            return Element::checkbox(sprintf('published[%s]', $member->getId()), $member->getPublished());
                        }
                    )
                ),

                'actions' => array(
                    'edit' => function($member){
                        return Icon::edit(
                            $this->url('Team:Admin:Member@editAction', $member->getId()),
                            $this->translate('Edit the member')
                        );
                    },

                    'remove' => function($member){
                        return Icon::remove(
                            $this->url('Team:Admin:Member@deleteAction', $member->getId()),
                            $this->translate('Remove this member')
                        );
                    }
                )
            ))); ?>

            <?php if (empty($members)): ?>
            <div class="center-block">
                <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No members'); ?></h2>
            </div>
            <?php endif; ?>
        </div>
    </form>

    <?php $this->loadPartial('paginator'); ?>

</div>
