<?php

use Krystal\Grid\Grid;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
		 <li><a href="<?php echo $this->url('Team:Admin:Member@addAction'); ?>"><i class="glyphicon glyphicon-user"></i> <?php $this->show('Add a member'); ?></a></li>
		 <li><a href="<?php echo $this->url('Team:Admin:Config@indexAction'); ?>"><i class="glyphicon glyphicon-tasks"></i> <?php $this->show('Configuration'); ?></a></li>
		 <li class="divider"></li>
		 <li class="dropdown-header"><?php $this->show('Actions'); ?></li>
		 
		 <?php if (!empty($members)): ?>
		 <li><a href="#" data-button="save-changes" data-url="<?php echo $this->url('Team:Admin:Member@tweakAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li><a href="#" data-button="remove-selected" data-url="<?php echo $this->url('Team:Admin:Member@deleteAction', null); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php else: ?>
		 
		 <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php endif; ?>
	  </ul>
	</div>
</div>

<?php $this->loadPartial('items-per-page', array('caption' => 'Team')); ?>

<form>
	<div class="table-responsive">
        <?= Grid::render($members, array(
            'batch' => true,
            'pk' => 'id',
            'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
            'columns' => array(
                array(
                    'column' => 'id',
                    'label' => '#'
                ),

                array(
                    'column' => 'photo',
                    'value' => function($member){
                        return Element::image($member->getImageUrl('400x200'), array('class' => 'img-responsive center-block'));
                    }
                ),

                array(
                    'column' => 'name'
                ),

                array(
                    'column' => 'order',
                    'value' => function($member){
                        return Element::number(sprintf('order[%s]', $member->getId()), $member->getOrder(), array('class' => 'form-control', 'min' => '0'));
                    }
                ),

                array(
                    'column' => 'published',
                    'value' => function($member){
                        return Element::checkbox(sprintf('published[%s]', $member->getId()), $member->getPublished());
                    }
                )
            ),

            'actions' => array(
                'edit' => function($member){
                    return Icon::edit(
                        $this->url('Team:Admin:Member@editAction', $member->getId()),
                        $this->translate('Edit the member')
                    );
                },

                'remove' => function($member){
                    return Icon::remove(
                        $this->url('Team:Admin:Member@deleteAction', $member->getId()),
                        $this->translate('Remove this member')
                    );
                }
            )

        ), $this->translator); ?>

		<?php if (empty($members)): ?>
		<div class="center-block">
            <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No members'); ?></h2>
		</div>
		<?php endif; ?>
	</div>
</form>

<?php $this->loadPartial('paginator'); ?>
