<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
    <div class="dropdown">
      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
        <i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?>
      </button>

      <div class="dropdown-menu">
         <a class="dropdown-item" href="<?php echo $this->url('Team:Admin:Member@addAction'); ?>"><i class="glyphicon glyphicon-user"></i> <?php $this->show('Add a member'); ?></a>
         <a class="dropdown-item" href="<?php echo $this->url('Team:Admin:Config@indexAction'); ?>"><i class="glyphicon glyphicon-tasks"></i> <?php $this->show('Configuration'); ?></a>
         <div class="dropdown-divider"></div>
         <div class="dropdown-header"><?php $this->show('Actions'); ?></div>
         <?php if (!empty($members)): ?>
         <a class="dropdown-item" href="#" data-button="save-changes" data-url="<?php echo $this->url('Team:Admin:Member@tweakAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a>
         <a class="dropdown-item" href="#" data-button="remove-selected" data-url="<?php echo $this->url('Team:Admin:Member@deleteAction', null); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a>
         <?php else: ?>

         <a class="dropdown-item disabled"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a>
         <a class="dropdown-item disabled"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a>
         <?php endif; ?>
      </div>
    </div>
</div>

<div class="card">
    <?php $this->loadPartial('items-per-page', array('caption' => 'Team')); ?>

    <form>
        <div class="table-responsive">
            <?= $this->widget(new GridViewWidget($members, array(
                'batch' => true,
                'pk' => 'id',
                'tableClass' => 'table table-hover table-bordered table-striped',
                'columns' => array(
                    array(
                        'column' => 'id',
                        'label' => '#'
                    ),

                    array(
                        'column' => 'photo',
                        'value' => function($member){
                            return Element::image($member->getImageUrl('400x200'), array('class' => 'img-fluid'));
                        }
                    ),

                    array(
                        'column' => 'name'
                    ),

                    array(
                        'column' => 'order',
                        'value' => function($member){
                            return Element::number(sprintf('order[%s]', $member->getId()), $member->getOrder(), array('class' => 'form-control', 'min' => '0'));
                        }
                    ),

                    array(
                        'column' => 'published',
                        'value' => function($member){
                            return Element::checkbox(sprintf('published[%s]', $member->getId()), $member->getPublished());
                        }
                    )
                ),

                'actions' => array(
                    'edit' => function($member){
                        return Icon::edit(
                            $this->url('Team:Admin:Member@editAction', $member->getId()),
                            $this->translate('Edit the member')
                        );
                    },

                    'remove' => function($member){
                        return Icon::remove(
                            $this->url('Team:Admin:Member@deleteAction', $member->getId()),
                            $this->translate('Remove this member')
                        );
                    }
                )
            ))); ?>

            <?php if (empty($members)): ?>
            <div class="center-block">
                <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No members'); ?></h2>
            </div>
            <?php endif; ?>
        </div>
    </form>

    <?php $this->loadPartial('paginator'); ?>

</div>
